# Generated by Django 5.1.2 on 2024-10-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://dummyimage.com/600x400/000/fff.png', max_length=500),
        ),
    ]
